export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

export const FETCHED_ALL_CATEGORIES = 'FETCHED_ALL_CATEGORIES';
export const FETCHED_ALL_PRODCUTS = 'FETCHED_ALL_PRODCUTS';

export const UPDATED_USER_CART = 'UPDATED_USER_CART';

export const FETCHED_ALL_ORDERS = 'FETCHED_ALL_ORDERS';
